# Generated by Django 2.2 on 2020-07-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_uri',
            field=models.URLField(max_length=500),
        ),
    ]
